# Project information
site_name: 'Colyseus 0.10.x'
site_description: 'Documentation for Colyseus Multiplayer Game Server for Node.js'
site_author: 'Endel Dreyer'
site_url: 'https://colyseus.io/'
edit_uri: 'https://github.com/colyseus/docs/edit/master/docs/'

# Deployment
remote_name: 'origin'
remote_branch: 'gh-pages'

# Repository
repo_name: 'colyseus/colyseus'
repo_url: 'https://github.com/colyseus/colyseus'

# Copyright
copyright: 'Copyright &copy; 2019 Endel Dreyer'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo-white.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - 'stylesheets/code-tabs.css'

extra_javascript:
  - 'javascripts/main.js'
  - 'javascripts/ads.js'

# Options
extra:
  search:
    language: 'en'
  social:
  - type: 'money'
    link: 'https://www.patreon.com/endel'
  - type: 'comments'
    link: 'https://discuss.colyseus.io'
  - type: 'globe'
    link: 'http://colyseus.io'
  - type: 'github'
    link: 'https://github.com/colyseus'
  - type: 'twitter'
    link: 'https://twitter.com/colyseus'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/game-std-io/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
      active_class: 'active'
      template: 'default'

# Nav menu
nav:
- 'Home': 'index.md'
- 'Getting started':
  - 'Server-side': 'getting-started/server.md'
  - 'JavaScript Client': 'getting-started/javascript-client.md'
  - 'Defold Engine Client': 'getting-started/defold-client.md'
  - 'Haxe Client': 'getting-started/haxe-client.md'
  - 'Cocos2d-x Client': 'getting-started/cocos2dx-client.md'
  - 'Unity3d Client': 'getting-started/unity3d-client.md'
  - 'Construct3 Client': 'getting-started/construct3-client.md'

# - 'Tutorials':
#   - ''

- 'Server API':
  - 'Server': 'server/api.md'
  - 'Room': 'server/room.md'
  - 'Client': 'server/client.md'
  - 'State Serialization': 'server/state-serialization.md'
  - 'Timing events': 'server/timing-events.md'
  - 'Authentication': 'server/authentication.md'
  - 'Presence': 'server/presence.md'
  - 'Graceful shutdown': 'server/graceful-shutdown.md'

- 'Client API':
  - 'Client': 'client/client.md'
  - 'Room': 'client/room.md'

- 'State Handling':
  - 'Overview': 'state/overview.md'
  - 'Schema (0.10.x)': 'state/schema.md'
  - 'Fossil Delta (0.9.x)': 'state/fossil-delta.md'

- 'Matchmaking': 'matchmaking.md'
- 'Authentication': 'authentication.md'
- 'Push Messages': 'push.md'

- 'Debugging': 'debugging.md'
- 'Deployment': 'deployment.md'
- 'Migrating':
  - '0.10.x': 'migrating/0.10.md'
  - '0.9.x': 'migrating/0.9.md'

- 'FAQ': 'faq.md'
