# Project information
site_name: 'Colyseus - Multiplayer Game Server for Node.js'
site_description: 'Documentation for Colyseus Multiplayer Game Server for Node.js'
site_author: 'gamestd.io'
site_url: 'https://colyseus.io/'
edit_uri: 'https://github.com/colyseus/docs/edit/master/docs/'

# Deployment
remote_name: 'origin'
remote_branch: 'gh-pages'

# Repository
repo_name: 'gamestdio/colyseus'
repo_url: 'https://github.com/gamestdio/colyseus'

# Copyright
copyright: 'Copyright &copy; 2018 Endel Dreyer'

# Documentation and theme
theme:
  name: 'material'
  language: 'en'
  logo: 'images/logo-white.png'
  favicon: 'images/favicon.png'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

extra_css:
  - 'stylesheets/code-tabs.css'

extra_javascript:
  - 'javascripts/main.js'

# Options
extra:
  search:
    language: 'en'
  social:
  - type: 'money'
    link: 'https://www.patreon.com/endel'
  - type: 'comments'
    link: 'https://discuss.colyseus.io'
  - type: 'globe'
    link: 'http://colyseus.io'
  - type: 'github'
    link: 'https://github.com/gamestdio'
  - type: 'twitter'
    link: 'https://twitter.com/gstdio'
  - type: 'linkedin'
    link: 'https://www.linkedin.com/company/game-std-io/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      linenums: False
      guess_lang: False
  - toc:
      permalink: True
  - markdown_fenced_code_tabs:
      single_block_as_tab: False
  - del_ins

# Nav menu
pages:
- 'Introduction': 'index.md'
- 'Getting started': 'getting-started.md'

- 'Concepts':
  - 'State synchronization': 'concept-state-synchronization.md'
  - 'Matchmaking': 'concept-matchmaking.md'

- 'Server-side':
  - 'Server': 'api-server.md'
  - 'Room': 'api-room.md'
  - 'Client': 'api-client.md'
  - 'Timing events': 'api-timing-events.md'
  - 'State management': 'api-room-state.md'
  - 'Authentication': 'api-authentication.md'
  - 'Graceful shutdown': 'api-graceful-shutdown.md'
  - 'Debugging': 'api-debugging.md'

- 'Client-side':
  - 'Overview': 'client-overview.md'
  - 'Room': 'client-room.md'
  - 'State synchronization': 'client-state-synchronization.md'

- 'Deployment': 'deployment.md'
- 'Migrating': 'migrating.md'

- 'FAQ': 'faq.md'
- 'More':
  - 'Roadmap': 'roadmap.md'
